# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
#
# You may wish to alter this file to override the set of languages analyzed,
# or to provide custom queries or build logic.
#
# ******** NOTE ********
# We have attempted to detect the languages in your repository. Please check
# the `language` matrix defined below to confirm you have the correct set of
# supported CodeQL languages.
#
name: ".net build"

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  dotnet:
    name: Build and deploy client app
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget
      - name: Build with .net
        run: |
          dotnet restore --locked-mode
          dotnet publish -a x64 --os win --self-contained true -c Release
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r client.zip bin/Release/net8.0/win-x64/publish
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: "dotnet"
          prerelease: true
          title: "Trinity Build, created at ${{ github.event.repository.updated_at}}"
          files: |
            client.zip